-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR AS B  
ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '세단' AND MONTH(A.START_DATE) = 10
ORDER BY CAR_ID DESC;

